=== vasuparepalli/scripts/CashManagementTransactionCommonV1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="CashManagementTransaction">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Header" type="HeaderType" />
				<xs:element ref="Detail" maxOccurs="unbounded" />
				<xs:element name="Trailer" type="TrailerType" />
			</xs:sequence>
			<xs:attribute name="schemaVersion" type="xs:string"
				default="1" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="Detail" type="DetailType" />
	
	<xs:complexType name="HeaderType">
		<xs:sequence>
			<xs:element name="PlanOrganization" type="PlanOrganizationType" />
			<xs:element ref="ActivityTimestamp" />
			<xs:element ref="LineOfBusiness" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="PlanOrganizationType">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:element name="ActivityTimestamp" type="xs:dateTime" />

	<xs:element name="LineOfBusiness">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="FEP" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:complexType name="DetailType">
		<xs:sequence>
			<xs:element ref="CycleDate" />
			<xs:element name="PlanCode" type="PlanCodeType" />
			<xs:element ref="Dcn" />
			<xs:element ref="SubscriberId" />
			<xs:element ref="TransactionId" />
			<xs:element ref="PayeeIdentifier" />
			<xs:element ref="ClaimPaidAmount" />
			<xs:element ref="DateGroupCode" />
			<xs:element ref="PlanType" />
			<xs:element ref="CoderId" minOccurs="0" />
			<xs:element ref="CashReceiptNumber" minOccurs="0" />
			<xs:element ref="OcProcessedDate" minOccurs="0" />
			<xs:element ref="TaxId" minOccurs="0" />
			<xs:element ref="CustomElements" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="CycleDate" type="xs:date" />
	
	<xs:simpleType name="PlanCodeType">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	
	<xs:element name="Dcn">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="14" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="SubscriberId">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="9" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="TransactionId">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="11" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

		<xs:element name="PayeeIdentifier">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="13" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="ClaimPaidAmount">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="currency" use="optional" default="dollars">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="dollars" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="DateGroupCode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="13" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="PlanType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="BASIC" />
				<xs:enumeration value="STD" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="CoderId">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="10" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="CashReceiptNumber">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="11" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="OcProcessedDate" type="xs:date" />

	<xs:element name="TaxId">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>

	<xs:element name="CustomElements">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CustomElement" type="CustomElementType"
					maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="CustomElementType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="TrailerType">
		<xs:sequence>
			<xs:element ref="RecordCount" />
			<xs:element ref="RecordTotal" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="RecordCount">
		<xs:simpleType>
			<xs:restriction base="xs:nonNegativeInteger" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="RecordTotal">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="currency" use="optional" default="dollars">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="dollars" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== vasuparepalli/scripts/FEP_Bridge_Premera_CM_430_20200312_001109.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<CashManagementTransaction xmlns="http://www.carefirst.com/CashManagementTransactionCommonV1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pm="http://www.carefirst.com/CashManagementTransactionPREMERAV1" xsi:schemaLocation="http://www.carefirst.com/CashManagementTransactionCommonV1 CashManagementTransactionCommonV1.xsd http://www.carefirst.com/CashManagementTransactionPREMERAV1 CashManagementTransactionPREMERAV1.xsd">
    <Header>
        <PlanOrganization>PREMERA</PlanOrganization>
        <ActivityTimestamp>2020-03-12T00:11:09.266-04:00</ActivityTimestamp>
        <LineOfBusiness>FEP</LineOfBusiness>
    </Header>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>84625U2325PM</Dcn>
        <SubscriberId>R11408579</SubscriberId>
        <TransactionId>46652225770</TransactionId>
        <PayeeIdentifier>1801851258</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">-1340</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">-1340</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>FOCUS</PlanType>
        <CoderId>430F309</CoderId>
        <OcProcessedDate>2019-03-12</OcProcessedDate>
        <TaxId>910565539</TaxId>
        <CustomElements>
            <CustomElement name="KeyerId">430F309</CustomElement>
        </CustomElements>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>84253U5807PM</Dcn>
        <SubscriberId>R50009395</SubscriberId>
        <TransactionId>45053112441</TransactionId>
        <PayeeIdentifier>1164580700</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">0</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">0</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>FOCUS</PlanType>
        <CoderId>430F203A</CoderId>
        <OcProcessedDate>2019-02-25</OcProcessedDate>
        <TaxId>910889551</TaxId>
        <CustomElements>
            <CustomElement name="KeyerId">430F203A</CustomElement>
        </CustomElements>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>84601E0557PM</Dcn>
        <SubscriberId>R50102885</SubscriberId>
        <TransactionId>47425185404</TransactionId>
        <PayeeIdentifier>1801851258</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">-648.14</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">-648.14</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>FOCUS</PlanType>
        <CoderId>430F309</CoderId>
        <OcProcessedDate>2019-04-04</OcProcessedDate>
        <TaxId>910565539</TaxId>
        <CustomElements>
            <CustomElement name="KeyerId">430F309</CustomElement>
        </CustomElements>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>84648Q8636PM</Dcn>
        <SubscriberId>R50102885</SubscriberId>
        <TransactionId>43365816525</TransactionId>
        <PayeeIdentifier>1801851258</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">-648.14</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">-648.14</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>STD</PlanType>
        <CoderId>430F309</CoderId>
        <OcProcessedDate>2019-04-04</OcProcessedDate>
        <TaxId>910565539</TaxId>
        <CustomElements>
            <CustomElement name="KeyerId">430F309</CustomElement>
        </CustomElements>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>84669L8663PM</Dcn>
        <SubscriberId>R50112052</SubscriberId>
        <TransactionId>40031150176</TransactionId>
        <PayeeIdentifier>1801851258</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">-1340</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">-1340</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>STD</PlanType>
        <CoderId>430F324</CoderId>
        <OcProcessedDate>2019-04-08</OcProcessedDate>
        <TaxId>910565539</TaxId>
        <CustomElements>
            <CustomElement name="KeyerId">430F324</CustomElement>
        </CustomElements>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>72122P1281PM</Dcn>
        <SubscriberId>R50174291</SubscriberId>
        <TransactionId>40116887344</TransactionId>
        <PayeeIdentifier>1992701825</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">-710.24</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">-337.24</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>FOCUS</PlanType>
        <CoderId>190F1080</CoderId>
        <OcProcessedDate>2018-10-31</OcProcessedDate>
        <TaxId>520445374</TaxId>
        <CustomElements>
            <CustomElement name="KeyerId">190F1080</CustomElement>
        </CustomElements>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>72122S6200PM</Dcn>
        <SubscriberId>R50174291</SubscriberId>
        <TransactionId>43544183352</TransactionId>
        <PayeeIdentifier>1992701825</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">-710.24</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">-337.24</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>STD</PlanType>
        <CoderId>190F1080</CoderId>
        <OcProcessedDate>2018-10-31</OcProcessedDate>
        <TaxId>520445374</TaxId>
        <CustomElements>
            <CustomElement name="KeyerId">190F1080</CustomElement>
        </CustomElements>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>80312H5313PM</Dcn>
        <SubscriberId>R50634735</SubscriberId>
        <TransactionId>45434178416</TransactionId>
        <PayeeIdentifier>R5063473501</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">-15304.94</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">-253.88</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>STD</PlanType>
        <CoderId>190F1080</CoderId>
        <OcProcessedDate>2018-10-31</OcProcessedDate>
        <CustomElements>
            <CustomElement name="KeyerId">190F1080</CustomElement>
        </CustomElements>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>80322N0265PM</Dcn>
        <SubscriberId>R50634735</SubscriberId>
        <TransactionId>43080118051</TransactionId>
        <PayeeIdentifier>R5063473502</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">-15304.94</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">-253.88</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>FOCUS</PlanType>
        <CoderId>190F1080</CoderId>
        <OcProcessedDate>2018-10-31</OcProcessedDate>
        <CustomElements>
            <CustomElement name="KeyerId">190F1080</CustomElement>
        </CustomElements>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>80322T0850PM</Dcn>
        <SubscriberId>R50634735</SubscriberId>
        <TransactionId>45667456117</TransactionId>
        <PayeeIdentifier>R5063473503</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">-15304.94</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">-253.88</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>STD</PlanType>
        <CoderId>190F1080</CoderId>
        <OcProcessedDate>2018-10-31</OcProcessedDate>
        <CustomElements>
            <CustomElement name="KeyerId">190F1080</CustomElement>
        </CustomElements>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>80352O2263PM</Dcn>
        <SubscriberId>R50634735</SubscriberId>
        <TransactionId>48432605446</TransactionId>
        <PayeeIdentifier>R5063473504</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">-15304.94</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">-253.88</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>BASIC</PlanType>
        <CoderId>190F1080</CoderId>
        <OcProcessedDate>2018-10-31</OcProcessedDate>
        <CustomElements>
            <CustomElement name="KeyerId">190F1080</CustomElement>
        </CustomElements>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <CycleDate>2020-03-11</CycleDate>
        <PlanCode>430</PlanCode>
        <Dcn>8452491652PM</Dcn>
        <SubscriberId>R50942620</SubscriberId>
        <TransactionId>42635674586</TransactionId>
        <PayeeIdentifier>1700037801</PayeeIdentifier>
        <PriorClaimPaidAmount currency="dollars">-506.58</PriorClaimPaidAmount>
        <ClaimPaidAmount currency="dollars">-506.58</ClaimPaidAmount>
        <DateGroupCode>BCP03112020</DateGroupCode>
        <PlanType>BASIC</PlanType>
        <CoderId>AUDIT</CoderId>
        <OcProcessedDate>2019-04-03</OcProcessedDate>
        <TaxId>352346161</TaxId>
        <CustomElements>
