=== vasuparepalli/scripts/GeneralLedgerTransactionCommonV1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="GeneralLedgerTransaction">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Header" type="HeaderType" />
				<xs:element ref="Detail" maxOccurs="unbounded" />
				<xs:element name="Trailer" type="TrailerType" />
			</xs:sequence>
			<xs:attribute name="schemaVersion" type="xs:string"
				default="1" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="Detail" type="DetailType" />

	<xs:complexType name="HeaderType">
		<xs:sequence>
			<xs:element name="PlanOrganization" type="PlanOrganizationType" />
			<xs:element ref="ActivityTimestamp" />
			<xs:element ref="LineOfBusiness" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="PlanOrganizationType">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:element name="ActivityTimestamp" type="xs:dateTime" />

	<xs:element name="LineOfBusiness">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="FEP" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:complexType name="DetailType">
		<xs:sequence>
			<xs:element ref="EntityCode" />
			<xs:element ref="AccountNumber" />
			<xs:element ref="CostCenter" />
			<xs:element ref="CostCenterPool" />
			<xs:element ref="Site" />
			<xs:element ref="Risk" />
			<xs:element ref="Product" />
			<xs:element ref="Market" />
			<xs:element ref="Operations" />
			<xs:element ref="Project" />
			<xs:element ref="CjaCode" />
			<xs:element ref="Future" />
			<xs:element ref="Source" />
			<xs:element ref="CycleDate" />
			<xs:element ref="GLAmount" />
			<xs:element ref="GLDescription" />
			<xs:element ref="ReversalFlag" />
			<xs:element ref="GLSource" />
			<xs:element ref="GLCategory" />
			<xs:element ref="CustomElements" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="EntityCode">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="AccountNumber">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="CostCenter">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="CostCenterPool">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="Site">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>

	<xs:element name="Risk">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>

	<xs:element name="Product">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="Market">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="Operations">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="Project">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>

	<xs:element name="CjaCode">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="Future">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="Source">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="CycleDate" type="xs:date" />

	<xs:element name="GLAmount">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="currency" use="optional" default="dollars">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="dollars" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="GLDescription">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>	

	<xs:element name="ReversalFlag">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>		
	
	<xs:element name="GLSource">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>		
	
	<xs:element name="GLCategory">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>		

	<xs:element name="CustomElements">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CustomElement" type="CustomElementType"
					maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="CustomElementType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="TrailerType">
		<xs:sequence>
			<xs:element ref="RecordCount" />
			<xs:element ref="RecordTotal" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="RecordCount">
		<xs:simpleType>
			<xs:restriction base="xs:nonNegativeInteger" />
		</xs:simpleType>
	</xs:element>

	<xs:element name="RecordTotal">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="currency" use="optional" default="dollars">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="dollars" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== vasuparepalli/scripts/FEP_Bridge_Premera_GL_430_20200312_001412.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GeneralLedgerTransaction xmlns="http://www.carefirst.com/GeneralLedgerTransactionCommonV1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pm="http://www.carefirst.com/GeneralLedgerTransactionPREMERAV1" xsi:schemaLocation="http://www.carefirst.com/GeneralLedgerTransactionCommonV1 GeneralLedgerTransactionCommonV1.xsd http://www.carefirst.com/GeneralLedgerTransactionPREMERAV1 GeneralLedgerTransactionPREMERAV1.xsd">
    <Header>
        <PlanOrganization>PREMERA</PlanOrganization>
        <ActivityTimestamp>2020-03-12T00:14:12.635-04:00</ActivityTimestamp>
        <LineOfBusiness>FEP</LineOfBusiness>
    </Header>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <EntityCode>100</EntityCode>
        <AccountNumber>51000</AccountNumber>
        <CostCenter>00000</CostCenter>
        <CostCenterPool>0000</CostCenterPool>
        <Site>0000</Site>
        <Risk>000</Risk>
        <Product>000</Product>
        <Market>000</Market>
        <Operations>000</Operations>
        <Project>0000</Project>
        <CjaCode>1997</CjaCode>
        <Future>0000</Future>
        <Source>FDDE</Source>
        <CycleDate>2020-03-11</CycleDate>
        <GLAmount>1316784.94</GLAmount>
        <GLDescription>VCHR 1A-FEP PLAN 430</GLDescription>
        <ReversalFlag/>
        <GLSource/>
        <GLCategory/>
        <CustomElements>
            <CustomElement name="RunGroup">FEPCareFirst</CustomElement>
            <CustomElement name="SequenceNumber1">1</CustomElement>
            <CustomElement name="OldCompany">9200</CustomElement>
            <CustomElement name="OldAccountNumber">51000</CustomElement>
            <CustomElement name="SourceCode">FE</CustomElement>
            <CustomElement name="ClaimPaidDate">2020-03-11</CustomElement>
            <CustomElement name="Description">FEP Claims</CustomElement>
            <CustomElement name="CurrencyCode">USD</CustomElement>
            <CustomElement name="TransactionAmount">+01316784.94</CustomElement>
            <CustomElement name="System">GL</CustomElement>
            <CustomElement name="PostingDate">2020-03-11</CustomElement>
            <CustomElement name="EffectDate">2020-03-11</CustomElement>
            <CustomElement name="Reference"/>
            <CustomElement name="UnitsAmount"/>
            <CustomElement name="BaseAmount"/>
            <CustomElement name="BaseRate"/>
            <CustomElement name="ProgramCode"/>
            <CustomElement name="AutoReverse"/>
            <CustomElement name="Activity"/>
            <CustomElement name="AccountCategory"/>
            <CustomElement name="DocumentNumber"/>
            <CustomElement name="ToBaseAmount"/>
            <CustomElement name="JournalBookNumber"/>
            <CustomElement name="Product">PPO</CustomElement>
            <CustomElement name="Segment">FEP</CustomElement>
            <CustomElement name="AttributeValue3"/>
            <CustomElement name="SequenceNumber2"/>
            <CustomElement name="NegativeAdjustment"/>
            <CustomElement name="UserAnalysis"/>
            <CustomElement name="ReportCurrencyOneAmount"/>
            <CustomElement name="ExchangeRate1"/>
            <CustomElement name="Decimal1"/>
            <CustomElement name="ReportCurrencyTwoAmount"/>
            <CustomElement name="ExchangeRate2"/>
            <CustomElement name="Decimal2"/>
        </CustomElements>
        <pm:LOB>330</pm:LOB>
        <pm:State>WA</pm:State>
        <pm:LOC>MED</pm:LOC>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <EntityCode>100</EntityCode>
        <AccountNumber>41000</AccountNumber>
        <CostCenter>00000</CostCenter>
        <CostCenterPool>0000</CostCenterPool>
        <Site>0000</Site>
        <Risk>000</Risk>
        <Product>000</Product>
        <Market>000</Market>
        <Operations>000</Operations>
        <Project>0000</Project>
        <CjaCode>1997</CjaCode>
        <Future>0000</Future>
        <Source>FDDE</Source>
        <CycleDate>2020-03-11</CycleDate>
        <GLAmount>-1316784.94</GLAmount>
        <GLDescription>VCHR 1A-FEP PLAN 430</GLDescription>
        <ReversalFlag/>
        <GLSource/>
        <GLCategory/>
        <CustomElements>
            <CustomElement name="RunGroup">FEPCareFirst</CustomElement>
            <CustomElement name="SequenceNumber1">2</CustomElement>
            <CustomElement name="OldCompany">9200</CustomElement>
            <CustomElement name="OldAccountNumber">41000</CustomElement>
            <CustomElement name="SourceCode">FE</CustomElement>
            <CustomElement name="ClaimPaidDate">2020-03-11</CustomElement>
            <CustomElement name="Description">FEP Claims</CustomElement>
            <CustomElement name="CurrencyCode">USD</CustomElement>
            <CustomElement name="TransactionAmount">-01316784.94</CustomElement>
            <CustomElement name="System">GL</CustomElement>
            <CustomElement name="PostingDate">2020-03-11</CustomElement>
            <CustomElement name="EffectDate">2020-03-11</CustomElement>
            <CustomElement name="Reference"/>
            <CustomElement name="UnitsAmount"/>
            <CustomElement name="BaseAmount"/>
            <CustomElement name="BaseRate"/>
            <CustomElement name="ProgramCode"/>
            <CustomElement name="AutoReverse"/>
            <CustomElement name="Activity"/>
            <CustomElement name="AccountCategory"/>
            <CustomElement name="DocumentNumber"/>
            <CustomElement name="ToBaseAmount"/>
            <CustomElement name="JournalBookNumber"/>
            <CustomElement name="Product">PPO</CustomElement>
            <CustomElement name="Segment">FEP</CustomElement>
            <CustomElement name="AttributeValue3"/>
            <CustomElement name="SequenceNumber2"/>
            <CustomElement name="NegativeAdjustment"/>
            <CustomElement name="UserAnalysis"/>
            <CustomElement name="ReportCurrencyOneAmount"/>
            <CustomElement name="ExchangeRate1"/>
            <CustomElement name="Decimal1"/>
            <CustomElement name="ReportCurrencyTwoAmount"/>
            <CustomElement name="ExchangeRate2"/>
            <CustomElement name="Decimal2"/>
        </CustomElements>
        <pm:LOB>330</pm:LOB>
        <pm:State>WA</pm:State>
        <pm:LOC>MED</pm:LOC>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <EntityCode>100</EntityCode>
        <AccountNumber>41000</AccountNumber>
        <CostCenter>00000</CostCenter>
        <CostCenterPool>0000</CostCenterPool>
        <Site>0000</Site>
        <Risk>000</Risk>
        <Product>000</Product>
        <Market>000</Market>
        <Operations>000</Operations>
        <Project>0000</Project>
        <CjaCode>1997</CjaCode>
        <Future>0000</Future>
        <Source>FDDE</Source>
        <CycleDate>2020-03-11</CycleDate>
        <GLAmount>21678.25</GLAmount>
        <GLDescription>VCHR 1A-FEP PLAN 430</GLDescription>
        <ReversalFlag/>
        <GLSource/>
        <GLCategory/>
        <CustomElements>
            <CustomElement name="RunGroup">FEPCareFirst</CustomElement>
            <CustomElement name="SequenceNumber1">3</CustomElement>
            <CustomElement name="OldCompany">9200</CustomElement>
            <CustomElement name="OldAccountNumber">41000</CustomElement>
            <CustomElement name="SourceCode">FE</CustomElement>
            <CustomElement name="ClaimPaidDate">2020-03-11</CustomElement>
            <CustomElement name="Description">FEP Claims</CustomElement>
            <CustomElement name="CurrencyCode">USD</CustomElement>
            <CustomElement name="TransactionAmount">+00021678.25</CustomElement>
            <CustomElement name="System">GL</CustomElement>
            <CustomElement name="PostingDate">2020-03-11</CustomElement>
            <CustomElement name="EffectDate">2020-03-11</CustomElement>
            <CustomElement name="Reference"/>
            <CustomElement name="UnitsAmount"/>
            <CustomElement name="BaseAmount"/>
            <CustomElement name="BaseRate"/>
            <CustomElement name="ProgramCode"/>
            <CustomElement name="AutoReverse"/>
            <CustomElement name="Activity"/>
            <CustomElement name="AccountCategory"/>
            <CustomElement name="DocumentNumber"/>
            <CustomElement name="ToBaseAmount"/>
            <CustomElement name="JournalBookNumber"/>
            <CustomElement name="Product">PPO</CustomElement>
            <CustomElement name="Segment">FEP</CustomElement>
            <CustomElement name="AttributeValue3"/>
            <CustomElement name="SequenceNumber2"/>
            <CustomElement name="NegativeAdjustment"/>
            <CustomElement name="UserAnalysis"/>
            <CustomElement name="ReportCurrencyOneAmount"/>
            <CustomElement name="ExchangeRate1"/>
            <CustomElement name="Decimal1"/>
            <CustomElement name="ReportCurrencyTwoAmount"/>
            <CustomElement name="ExchangeRate2"/>
            <CustomElement name="Decimal2"/>
        </CustomElements>
        <pm:LOB>330</pm:LOB>
        <pm:State>WA</pm:State>
        <pm:LOC>MED</pm:LOC>
    </Detail>
    <Detail xsi:type="pm:DetailTypePREMERA">
        <EntityCode>100</EntityCode>
        <AccountNumber>51000</AccountNumber>
        <CostCenter>00000</CostCenter>
        <CostCenterPool>0000</CostCenterPool>
        <Site>0000</Site>
        <Risk>000</Risk>
        <Product>000</Product>
        <Market>000</Market>
        <Operations>000</Operations>
        <Project>0000</Project>
        <CjaCode>1997</CjaCode>
        <Future>0000</Future>
        <Source>FDDE</Source>
        <CycleDate>2020-03-11</CycleDate>
        <GLAmount>-21678.25</GLAmount>
        <GLDescription>VCHR 1A-FEP PLAN 430</GLDescription>
        <ReversalFlag/>
        <GLSource/>
        <GLCategory/>
